# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbc09200f8150a97c5de1c196bf59d9dd57c3ca0e18f2a63a89df57476c65e40bdf42e995ac55cc7c1c90b30c052ec03dbcd5fc91f7a94b8c5a45afa3802ac1

test:
  secret_key_base: e7fefd668e2adddb1dfc8145b457e8fd2f6763aa42389cf0ba4d88753cb08e1c5806bcba415a2f84dc3139a838d272e76e6e1c068919d1b201056f6b7318f086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
